# Generated by Django 2.0.7 on 2018-08-10 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BuyBots_app', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('id_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuyBots_app.Comment')),
            ],
        ),
    ]
