# Generated by Django 2.0.7 on 2018-08-10 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BuyBots_app', '0003_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='id_bot',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='BuyBots_app.Bot'),
            preserve_default=False,
        ),
    ]
