# Generated by Django 2.0.7 on 2018-08-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuyBots_app', '0004_comment_id_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
