# Generated by Django 2.0.7 on 2018-08-10 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BuyBots_app', '0005_comment_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='login',
        ),
        migrations.RemoveField(
            model_name='client',
            name='password',
        ),
    ]
