# Generated by Django 2.1 on 2018-08-13 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BuyBots_app', '0009_auto_20180811_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
