# Generated by Django 2.1 on 2018-08-13 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BuyBots_app', '0010_auto_20180813_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='id_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BuyBots_app.Category'),
        ),
    ]
