# Generated by Django 2.1 on 2018-08-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuyBots_app', '0012_auto_20180813_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='eng_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
