# Generated by Django 2.1 on 2018-08-15 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BuyBots_app', '0012_auto_20180813_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bot',
            old_name='name',
            new_name='nameBot',
        ),
        migrations.RenameField(
            model_name='bot',
            old_name='id_category',
            new_name='nameCategory',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='nameCategory',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='id_client',
            new_name='id_user',
        ),
    ]
