# Generated by Django 2.1 on 2018-08-15 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BuyBots_app', '0013_auto_20180815_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bot',
            old_name='nameBot',
            new_name='name_bot',
        ),
        migrations.RenameField(
            model_name='bot',
            old_name='nameCategory',
            new_name='name_category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='nameCategory',
            new_name='name_category',
        ),
    ]
