# Generated by Django 2.1 on 2018-08-14 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BuyBots_app', '0013_bot_eng_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bot',
            old_name='eng_name',
            new_name='en_name',
        ),
    ]
