# Generated by Django 2.1 on 2018-08-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuyBots_app', '0014_auto_20180814_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='en_full_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
