# Generated by Django 2.1 on 2018-08-16 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BuyBots_app', '0014_auto_20180815_2142'),
        ('BuyBots_app', '0015_developer_en_full_name'),
    ]

    operations = [
    ]
